- name: Install SBCL and some other dependencies
  # OpenSSL is used by install_quicklisp.sh.
  # macOS curl is too old to talk to beta.quicklisp.org.
  x_macports:
    state: present
    name: [sbcl, openssl, curl]
  become: yes

- name: Install Quicklisp
  script: install_quicklisp.sh
  args:
    creates: '{{ ansible_env.HOME }}/quicklisp'
