other_software_macports_common:
  - aspell
  - aspell-dict-en
  - bash-completion
  - bat
  - ccache
  - colordiff
  - coreutils
  - ctags
  - direnv
  - dsh
  - emacs-app
  - fd
  - ffmpeg +nonfree
  - figlet
  - file
  - fping
  - fswatch
  - fzf
  - git
  - gnupg2
  - gnuplot
  - graphviz +rsvg
  - grep
  - gunits
  - iperf3
  - jq
  - less
  - lftp
  - lnav
  - mercurial
  - mtr
  - ncdu
  - neomutt
  - nmap
  # I officially hate picking a JDK build now.  My top choices from
  # what MacPorts offers are going to be, in descending order of
  # confidence:
  # * Azul Zulu Community (Azul has been involved in JDK for a long time)
  # * Temurin (AKA Adoptium, née AdoptOpenJDK)
  # * Oracle (actually open OpenJDK only supported for last release or
  #   something?? otherwise you get audited up the ass)
  # * SAP (major contributor to JDK, but why do they ship their own CA??)
  # * Anything else
  - openjdk18-zulu
  - openssh +gsskex
  - p7zip
  - parallel
  - patchutils
  - pinentry-mac
  # Poppler has pdfunite to combine PDF files
  - poppler
  - proselint
  - pspg
  - pstree
  - pv
  - qrencode
  # Note that Python is explicitly installed in another task, for
  # Ansible's benefit.  Python 2 and 3 are also installed by role
  # software_dev_python.
  - ripgrep +pcre
  - rlwrap
  - samba4
  - sleepwatcher
  - socat
  - sox
  - tidy
  - tree
  - unrar
  - watch
  # 2021-03-29: perl5 ports were being built with macOS SDK version
  # hard-coded.  See
  # https://github.com/macports/macports-ports/pull/10181 for example.
  # I fixed this by rebuilding the appropriate perl5* port from
  # source.
  - weechat +aspell+python310+scheme+perl+lua+tls
  - xsv
  - youtube-dl
  - zoxide

other_software_macports: '{{ other_software_macports_common }}'

other_software_system_casks_common:
  # Could MAS this, but 1Pass might get updates directly from
  # AgileBits a little faster than MAS.  Otherwise, should be no
  # difference.  AgileBits says in their forums that the version
  # direct from them is sandboxed just like the MAS version.
  - 1password
  # Burp has its own installer that installs to /Applications.
  # 2020-06-30: Breaks under quarantine
  # https://forum.portswigger.net/thread/install-macos-catalina-344b229e78f65
  - burp-suite
  - homebrew/cask-versions/firefox-developer-edition
  - intel-power-gadget
  - google-chrome
  - istat-menus
  - osxfuse
  #XXX - parallels
  - tunnelblick
  - wireshark
  # Nice side effect of XQuartz: DISPLAY environment variable gets
  # set.  This is necessary for OpenSSH to even think about calling
  # ssh-askpass, which is necessary if you want it to prompt you for
  # things like "should I add this key to ssh-agent?"
  - xquartz

other_software_system_casks: '{{ other_software_system_casks_common }}'

other_software_user_casks_common:
  - airfoil
  - alfred
  - alt-tab
  - appcleaner
  - audio-hijack
  - bartender
  - bettertouchtool
  - calibre
  - dash
  - ghidra
  - grandperspective
  - hammerspoon
  - handbrake
  - insomnia
  - iterm2
  - knockknock
  - libreoffice
  - loopback
  - micro-snitch
  - plex
  - silentknight
  - soundsource
  - the-unarchiver
  - tor-browser
  - vlc

other_software_user_casks: '{{ other_software_user_casks_common }}'

# MsgFiler is installed elsewhere.  Presumably Xcode is also installed
# elsewhere.
other_software_mac_app_store_common:
  - [1440147259, /Applications/AdGuard for Safari.app]
  - [824183456, /Applications/Affinity Photo.app]
  - [937984704, /Applications/Amphetamine.app]
  - [784801555, /Applications/Microsoft OneNote.app]
  - [1480933944, /Applications/Vimari.app]

other_software_mac_app_store: '{{ other_software_mac_app_store_common}}'

other_software_pipx_python: '{{ macports_python_3 }}'

other_software_pipx_common:
  - magic-wormhole
  - proselint
  - visidata
  - ydiff

other_software_pipx: '{{ other_software_pipx_common }}'

other_software_preferences_common:
  com.agilebits.onepassword7:
    - [
        "ShortcutRecorder BrowserActivation",
        dict,
        {
            "keyCode": -1,
            "modifierFlags": 0,
            "modifiers": 0,
        }
      ]
    - [
        "ShortcutRecorder GlobalActivation",
        dict,
        {
            "keyChars": "1",
            "keyCharsIgnoringModifiers": "!",
            "keyCode": 18,
            "modifierFlags": 393216,
            "modifiers": 4608,
        }
      ]
    - [
        "ShortcutRecorder GlobalLock",
        dict,
        {
            "keyCode": -1,
            "modifierFlags": 0,
            "modifiers": 0,
        }
      ]

  com.adguard.safari.AdGuard:
    - [NSFullScreenMenuItemEverywhere, bool, false]

  com.runningwithcrayons.Alfred-Preferences:
    - [syncfolder, string, '~/Dropbox']

  ~/Library/Containers/com.if.Amphetamine/Data/Library/Preferences/com.if.Amphetamine:
    - ["Default Duration", int, 14]
    - ["End Session On Low Battery", int, 1]
    - ["Hide Dock Icon", int, 1]
    - ["Icon Style", int, 5]
    - ["Ignore Battery on AC", int, 1]
    - ["Lower Icon Opacity", int, 1]
    - ["Session End Time Calcuation", int, 1]
    - ["Show Welcome Window", int, 0]

  com.hegenberg.BetterTouchTool:
    - [windowSnappingEnabled, bool, false]

  com.kapeli.dashdoc:
    - [shouldSyncGeneral, int, 1]
    - [shouldSyncDocsets, int, 1]
    - [shouldSyncBookmarks, int, 1]
    # Seems like sync is not getting set up.
    - [syncFolderPath, string, '~/Dropbox/app_sync/Dash']
    - [DHNotificationNestedResultTip, bool, true]
    - [DHNotificationTableOfContentsTip, bool, true]
    - [DHNotificationFindTip, bool, true]

  com.googlecode.iterm2:
    - [LoadPrefsFromCustomFolder, int, 1]
    - [PrefsCustomFolder, string, '{{ dropbox_dir }}/app_sync/iTerm']
    - [NoSyncNeverRemindPrefsChangesLostForFile, bool, true]
    - [NoSyncNeverRemindPrefsChangesLostForFile_selection, int, 0]

  net.tunnelblick.tunnelblick:
    - [keyboardShortcutIndex, int, 0]

  com.surteesstudios.Bartender:
    - [HideItemsWhenShowingOthers, bool, false]
    - [ClickingMenuBarTogglesBartender, bool, false]
    - [MouseOverMenuBarTogglesBartender, bool, false]
    - [ReduceMenuItemSpacing, int, 1]
    - [ReduceUpdateCheckFrequencyWhenOnBattery, bool, true]

  com.lwouis.alt-tab-macos:
    - [windowDisplayDelay, int, 70]
    - [nextWindowShortcut2, string, ""]

other_software_preferences: '{{ other_software_preferences_common }}'

other_software_add_dock_common:
  - /Applications/Firefox Developer Edition.app
  - ~/Applications/iTerm.app

other_software_add_dock: '{{ other_software_add_dock_common }}'

other_software_system_audio_units_dir: /Library/Audio/Plug-Ins/Components
other_software_user_audio_units_dir: >-
  {{ ansible_env.HOME }}/Library/Audio/Plug-Ins/Components
