other_software_homebrew_common:
  - aspell
  - bash-completion
  - bat
  - ccache
  - colordiff
  - coreutils
  - ctags
  - direnv
  - dsh
#  - emacs-app
  - fd
  - figlet
  - file-formula
  - fping
  - fswatch
  - fzf
  - git
  - gnupg
  - gnuplot
  - graphviz
  - grep
  - gnu-units
  - iperf3
  - jq
  - less
  - lftp
  - lnav
  - mercurial
  - miller
  - mtr
  - ncdu
  - neomutt
  - nmap
  # I officially hate picking a JDK build now.  My top choices in
  # descending order of confidence:
  #
  # * Azul Zulu Community (Azul has been involved in JDK for a long time)
  # * Amazon Corretto
  # * Temurin (AKA Adoptium, née AdoptOpenJDK)
  # * Oracle (actually open OpenJDK only supported for last release or
  #   something?? otherwise you get audited up the ass)
  # * SAP (major contributor to JDK, but why do they ship their own CA??)
  # * Anything else
  - openssh
  - p7zip
  - parallel
  - patchutils
  - pinentry-mac
  # Poppler has pdfunite to combine PDF files
  - poppler
  - proselint
  - pspg
  - pstree
  - pv
  - qrencode
  # Do I want this on my personal Mac?  I use it at work.
  - restic
  - ripgrep
  - rlwrap
  - samba
  - sleepwatcher
  - socat
  - sox
  - tidy-html5
  - tree
  - watch
  - weechat
  - xsv
  - zoxide

other_software_homebrew: '{{ other_software_homebrew_common }}'

other_software_system_casks_common:
  # Could MAS this, but 1Pass might get updates directly from
  # AgileBits a little faster than MAS.  Otherwise, should be no
  # difference.  AgileBits says in their forums that the version
  # direct from them is sandboxed just like the MAS version.
  - 1password
  - 1password-cli
  # Burp has its own installer that installs to /Applications.
  # 2020-06-30: Breaks under quarantine
  # https://forum.portswigger.net/thread/install-macos-catalina-344b229e78f65
  - burp-suite
  - homebrew/cask-versions/firefox-developer-edition
  - homebrew/cask-versions/zulu21
  - google-chrome
  - istat-menus
  - macfuse
  - wireshark
  # Nice side effect of XQuartz: DISPLAY environment variable gets
  # set.  This is necessary for OpenSSH to even think about calling
  # ssh-askpass, which is necessary if you want it to prompt you for
  # things like "should I add this key to ssh-agent?"
  - xquartz

other_software_system_casks: '{{ other_software_system_casks_common }}'

other_software_user_casks_common:
  - alfred
  - alt-tab
  - audio-hijack
  - bartender
  - bettertouchtool
  - dash
  - hammerspoon
  - intellij-idea
  # Using beta because (1) has 1Password support, and (2) 3.5 has been
  # in beta since 2021, apparently.
  - iterm2-beta
  - knockknock
  - loopback
  - micro-snitch
  - pycharm
  # This is mostly for unrar.
  - rar
  - silentknight
  - soundsource
  - suspicious-package
  - the-unarchiver

other_software_user_casks: '{{ other_software_user_casks_common }}'

# MsgFiler is installed elsewhere.  Presumably Xcode is also installed
# elsewhere.
other_software_mac_app_store_common:
  - [1440147259, /Applications/AdGuard for Safari.app]
  # NOTE: OneNote is installed in a common place because I snarf fonts
  # out of it.  Work machine may not like this...
  - [784801555, /Applications/Microsoft OneNote.app]
  - [1289583905, /Applications/Pixelmator Pro.app]
  - [1480933944, /Applications/Vimari.app]

other_software_mac_app_store: '{{ other_software_mac_app_store_common }}'

other_software_pipx_common:
  - magic-wormhole
  - proselint
  - visidata
  - ydiff

other_software_pipx: '{{ other_software_pipx_common }}'

other_software_preferences_common:
  com.adguard.safari.AdGuard:
    - [NSFullScreenMenuItemEverywhere, bool, false]

  com.googlecode.iterm2:
    - [EnterCopyModeAutomatically, bool, false]

  com.hegenberg.BetterTouchTool:
    - [windowSnappingEnabled, bool, false]

  com.kapeli.dashdoc:
    - [DHNotificationNestedResultTip, bool, true]
    - [DHNotificationTableOfContentsTip, bool, true]
    - [DHNotificationFindTip, bool, true]

  com.lwouis.alt-tab-macos:
    - [windowDisplayDelay, int, 70]
    - [nextWindowShortcut2, string, ""]

  com.surteesstudios.Bartender:
    - [HideItemsWhenShowingOthers, bool, false]
    - [ClickingMenuBarTogglesBartender, bool, false]
    - [MouseOverMenuBarTogglesBartender, bool, false]
    - [ReduceMenuItemSpacing, int, 1]
    - [ReduceUpdateCheckFrequencyWhenOnBattery, bool, true]

other_software_preferences: '{{ other_software_preferences_common }}'

other_software_add_dock_common:
  - /Applications/Firefox Developer Edition.app
  - ~/Applications/iTerm.app

other_software_add_dock: '{{ other_software_add_dock_common }}'

other_software_system_audio_units_dir: /Library/Audio/Plug-Ins/Components
other_software_user_audio_units_dir: >-
  {{ ansible_env.HOME }}/Library/Audio/Plug-Ins/Components
