- hosts: all
  roles:
    - {role: pkg_facts, tags: [always]}
    - {role: macos_system, tags: [macos_system]}
    - {role: macports, tags: [macports]}
    - {role: software_macfit, tags: [software_macfit]}
    - {role: software_mactex, tags: [software_mactex]}
    - {role: fonts, tags: [fonts]}
    - {role: macos_prefs, tags: [macos_prefs]}
    - {role: software_emacs, tags: [software_emacs]}
    - {role: dotfiles, tags: [dotfiles]}
    - {role: software_vim, tags: [software_vim]}
    - {role: software_misc, tags: [software_misc]}
  environment:
    PATH: '/opt/local/bin:{{ ansible_env.PATH }}'
