- hosts: all
  roles:
    - {role: macos_facts, tags: [always]}
    - {role: macos_system, tags: [macos_system]}
    # Force install of MacPorts before macos_prefs so we get the fast
    # PyObjC.  See roles/macports/tasks/main.yaml for more
    # information.
    - {role: macports, tags: [macports]}
    - {role: macos_prefs, tags: [macos_prefs]}
    - {role: software_emacs, tags: [software_emacs]}
    - {role: dotfiles, tags: [dotfiles]}
    - {role: software_vim, tags: [software_vim]}
    - {role: software_tmux, tags: [software_tmux]}
    - {role: software_dropbox, tags: [software_dropbox]}
    # Arguably I don't directly care about dockutil being installed,
    # but I do directly care about the fact that it cleans most of the
    # default macOS icons off my dock.
    - {role: software_dockutil, tags: [software_dockutil]}
    - {role: software_dev_clojure, tags: [software_dev_clojure]}
    - {role: software_dev_haskell, tags: [software_dev_haskell]}
    - {role: software_dev_lisp, tags: [software_dev_lisp]}
    - {role: software_dev_python, tags: [software_dev_python]}
    - {role: software_dev_ruby, tags: [software_dev_ruby]}
    - {role: software_dev_shell, tags: [software_dev_shell]}
    - {role: software_dev_sql, tags: [software_dev_sql]}
    - {role: software_dev_web, tags: [software_dev_web]}
    - {role: other_software, tags: [other_software]}
    - {role: mail_plug_ins, tags: [mail_plug_ins]}
    - {role: software_mactex, tags: [software_mactex]}
    - {role: software_sketch, tags: [software_sketch]}
    - {role: fonts, tags: [fonts]}
  environment:
    PATH: '/opt/local/bin:{{ ansible_env.PATH }}'
