- hosts: all
  pre_tasks:
    - name: Make sure you typed the sudo password right
      command:
        argv: ['true']
      become: yes
      changed_when: false
      tags: [always]

  roles:
    - {role: macos_facts, tags: [always]}
    - {role: macos_system_common, tags: [macos_system_common]}

- hosts: personal_machines
  roles:
    - {role: macos_system_personal, tags: [macos_system_personal]}
    - {role: macos_prefs, tags: [macos_prefs]}
    - {role: software_emacs, tags: [software_emacs]}
    - {role: dotfiles, tags: [dotfiles]}
    - {role: software_vim, tags: [software_vim]}
    - {role: software_tmux, tags: [software_tmux]}
    - {role: software_dropbox, tags: [software_dropbox]}
    # Arguably I don't directly care about dockutil being installed,
    # but I do directly care about the fact that it cleans most of the
    # default macOS icons off my dock.
    - {role: software_dockutil, tags: [software_dockutil]}
    - {role: software_dev_clojure, tags: [software_dev_clojure]}
    - {role: software_dev_lisp, tags: [software_dev_lisp]}
    - {role: software_dev_python, tags: [software_dev_python]}
    - {role: software_dev_shell, tags: [software_dev_shell]}
    - {role: software_dev_sql, tags: [software_dev_sql]}
    - {role: software_dev_web, tags: [software_dev_web]}
    - {role: other_software, tags: [other_software]}
    - {role: software_mactex, tags: [software_mactex]}
    - {role: fonts, tags: [fonts]}
    - {role: software_dev_go, tags: [software_dev_go]}
    - {role: software_dev_haskell, tags: [software_dev_haskell]}
    - {role: software_dev_ruby, tags: [software_dev_ruby]}
    - {role: software_postgresql, tags: [software_postgresql]}
    - {role: software_gocryptfs, tags: [software_gocryptfs]}
    # Not using this for now.
    #- {role: software_hugo, tags: [software_hugo]}
  environment:
    PATH: '/opt/local/bin:{{ homebrew_bin }}:/Library/TeX/texbin:{{ ansible_env.PATH }}'

- hosts: work_machines
  roles:
    - {role: macos_prefs, tags: [macos_prefs]}
    - {role: software_emacs, tags: [software_emacs]}
    - {role: dotfiles, tags: [dotfiles]}
    - {role: software_vim, tags: [software_vim]}
    - {role: software_tmux, tags: [software_tmux]}
    - {role: software_dockutil, tags: [software_dockutil]}
    - {role: software_dev_python, tags: [software_dev_python]}
    - {role: software_dev_shell, tags: [software_dev_shell]}
    - {role: software_dev_sql, tags: [software_dev_sql]}
    - {role: other_software, tags: [other_software]}
    - {role: software_postgresql, tags: [software_postgresql]}
    - {role: fonts, tags: [fonts]}
  environment:
    PATH: '/opt/local/bin:{{ homebrew_bin }}:/Library/TeX/texbin:{{ ansible_env.PATH }}'
