- hosts: all
  roles:
    - {role: macos_system, tags: [macos_system]}
    - {role: macports, tags: [macports]}
    - {role: software_emacs, tags: [software_emacs]}
  environment:
    PATH: '/opt/local/bin:{{ ansible_env.PATH }}'
