- hosts: all
  roles:
    - {role: pkg_facts, tags: [always]}
    - {role: macos_system, tags: [macos_system]}
    - {role: software_xcode, tags: [software_xcode]}
    - {role: macports, tags: [macports]}
    - {role: software_mactex, tags: [software_mactex]}
    - {role: fonts, tags: [fonts]}
    - {role: macos_prefs, tags: [macos_prefs]}
    - {role: software_emacs, tags: [software_emacs]}
    - {role: dotfiles, tags: [dotfiles]}
    - {role: software_vim, tags: [software_vim]}
    - {role: software_dropbox, tags: [software_dropbox]}
    - {role: python_venvs, tags: [python_venvs]}
    - {role: software_dev_python, tags: [software_dev_python]}
    - {role: haskell_stack, tags: [haskell_stack]}
    - {role: software_dev_haskell, tags: [software_dev_haskell]}
    - {role: software_dev_shell, tags: [software_dev_shell]}
    - {role: other_software, tags: [other_software]}
    - {role: mail_plug_ins, tags: [mail_plug_ins]}
  environment:
    PATH: '/opt/local/bin:{{ ansible_env.PATH }}'
