- name: Install MacPorts packages needed for my blog
  x_macports:
    state: present
    name: [hugo +extended, '{{ software_hugo_pygments_port_name }}']
  become: yes

- name: 'Make "pygments" run {{ software_hugo_pygments_port_name }} in MacPorts'
  command: port select --set pygments {{ software_hugo_pygments_port_name | quote }}
  args:
    creates: /opt/local/bin/pygmentize
  become: yes

- name: Install web development packages from NPM
  npm:
    state: present
    global: yes
    name: '{{ item }}'
  loop:
    - netlify-cli
