- name: Install MacPorts
  script: install_macports.py
  args:
    creates: /opt/local/bin/port
  become: true

- name: Configure variants
  lineinfile:
    path: /opt/local/etc/macports/variants.conf
    line: '{{ item }}'
    state: present
  loop:
    - '+no_x11'
    - '-x11'
    - '+bash_completion'
  become: true

# macOS system Python has much slower PyObjC imports, for purposes of
# my x_osx_defaults module.  Let's try and use the faster one from
# MacPorts from now on.

- name: Install Python and PyObjC
  x_macports:
    name:
      - python27
      - py27-pyobjc-cocoa
  become: true
  tags: [slow]

- name: Check for MacPorts Python 2
  stat:
    path: '{{ macports_python_2 }}'
  register: macports_python_2_stat
  tags: [always]

- name: Change Ansible's Python 2 interpreter to Python from MacPorts
  set_fact:
    ansible_python_interpreter: /opt/local/bin/python2.7
  when: 'macports_python_2_stat.stat.exists'
  tags: [always]
