- name: Install MacPorts
  script: install_macports.py
  args:
    creates: /opt/local/bin/port
  become: true

- name: Configure variants
  lineinfile:
    path: /opt/local/etc/macports/variants.conf
    line: '{{ item }}'
    state: present
  loop:
    - '+no_x11'
    - '-x11'
    - '+bash_completion'
  become: true

# macOS system Python has much slower PyObjC imports, for purposes of
# my x_osx_defaults module.  Let's try and use the faster one from
# MacPorts from now on.

- name: Install Python and PyObjC
  x_macports:
    name:
      - python27
      - py27-pyobjc-cocoa
  become: true
  tags: [slow]

- name: Check for MacPorts Python 2
  command:
    argv: ['{{ macports_python_2 }}', '-']
    stdin: |
      import sys
      try:
        import CoreFoundation
      except ImportError:
        sys.exit(101)
      sys.exit(0)
  register: macports_python_2_check
  failed_when: 'macports_python_2_check.rc not in (0, 101)'
  changed_when: False
  tags: [always]

- name: Change Ansible's Python 2 interpreter to Python from MacPorts
  set_fact:
    ansible_python_interpreter: '{{ macports_python_2 }}'
  when: 'macports_python_2_check.rc == 0'
  tags: [always]
