default_ports:
  - aspell
  - aspell-dict-en
  - bash-completion
  - ccache
  - colordiff
  - coreutils
  - ctags
  - emacs-app
  - fasd
  - fd
  - ffmpeg +nonfree
  - figlet
  - file
  - fping
  - fswatch
  - fzf
  - git
  - graphviz +rsvg
  - grep
  - gunits
  - iperf3
  - jq
  - less
  - lftp
  - mercurial
  - mp3splt
  - mtr
  - neomutt
  - nmap
  - openjdk11
  - openssh +gsskex
  - p7zip
  - parallel
  - patchutils
  - pstree
  - pv
  # Note that python27 is explicitly installed in another task, for
  # Ansible's benefit.  python27 and python37 are also installed by
  # software_dev_python.
  - ripgrep
  - rlwrap
  - samba3
  - sleepwatcher
  - socat
  - sox
  - sshfs
  - tidy
  - tmux
  - unrar
  - watch
  - youtube-dl

macports_python_2: /opt/local/bin/python2.7
