- name: Install Homebrew default Python
  homebrew:
    update_homebrew: true
    state: present
    name: python3

- name: Install Python development packages from Homebrew
  homebrew:
    state: present
    name: pyright

- name: Install Python 3 development tools
  community.general.pipx:
    name: '{{ item }}'
    state: '{{ software_dev_python_pipx_state }}'
    executable: '{{ homebrew_bin }}/pipx'
  loop:
    - flake8
    - pylint
    - ipython
    - isort
    - black
    - 'darker[isort]'
    - mypy
