- name: Install pipx
  homebrew:
    update_homebrew: true
    name: pipx
    state: present

- name: Install Python 3 development tools
  community.general.pipx:
    name: '{{ item }}'
    state: '{{ software_dev_python_pipx_state }}'
  loop:
    - flake8
    - pylint
    - ipython
    - isort
    - black
    - 'darker[isort]'
    - mypy
