- name: Install Python 2 development tools
  include_tasks: install_python_dev_tool.yaml
  loop:
    - package: flake8
    - package: pylint
    - package: ipython
    - package: jedi
    - package: gnureadline
  vars:
    virtualenv: '{{ user_py2_venv_dir }}'

- name: Fix gnureadline in Python 2
  file:
    state: link
    src: site-packages/readline.py
    dest: '{{ user_py2_venv_dir }}/lib/python2.7/readline.py'

- name: Install Python 3 development tools
  include_tasks: install_python_dev_tool.yaml
  loop:
    - package: flake8
    - package: pylint
    - package: ipython
    - package: jedi
    - package: black
      bins: [black]
    - package: isort
      bins: [isort]
  vars:
    virtualenv: '{{ user_py3_venv_dir }}'

# GNU readline + macOS + Python = still a pain in the ass
#
# The trick is that we need python-gnureadline to get installed into a
# directory that we can put on sys.path *before* the built-in
# lib-dynload, where Python will find the readline module built
# against libedit.
#
# So we:
#
# 1. Abuse setup.py --install-lib to put python-gnureadline somewhere
#    entirely outside Python's normal lib path
#    ($VIRTUAL_ENV/lib/pythonX.Y).
#
# 2. Drop a readline_path.pth file into the site-packages dir that
#    *executes* at Python startup...
#
# 3. ...a readline_path.py script we have also dropped into
#    site-packages that forcibly inserts our install-lib directory
#    from step 1 onto sys.path *before* the system directories.
#
# I used to use easy_install, which conveniently installed into a
# subdirectory anyway, but easy_install is all but abandoned.  Its
# Ansible module actually fails nowadays because easy_install
# --dry-run breaks installing python-gnureadline.
#
# If I used actual virtualenv instead of the built-in venv, I think I
# could use the same fix I use for Python 2, above.  But I'm stubborn.

- name: Install gnureadline for Python 3 with easy_install
  pip:
    virtualenv: '{{ user_py3_venv_dir }}'
    name: gnureadline
    # Argh (no pun intended), why doesn't extra_args take a list?
    extra_args: "--install-option --install-lib={{ software_dev_python_py3_gnureadline_dir | quote }}"
    state: present

- name: Install readline_path.py
  template:
    src: readline_path.py
    dest: '{{ user_py3_venv_dir }}/lib/python3.8/site-packages/'

- name: Install readline_path.pth
  copy:
    content: |
      import readline_path
    dest: '{{ user_py3_venv_dir }}/lib/python3.8/site-packages/readline_path.pth'
