- name: Install Bash
  x_macports:
    state: present
    name: bash
  become: true

- name: Change user's shell to MacPorts Bash
  user:
    name: '{{ ansible_user_id }}'
    shell: /opt/local/bin/bash
    create_home: no
  become: true

- name: Clone lnmgr repository
  git:
    repo: '{{ lnmgr_remote_repo }}'
    dest: '{{ lnmgr_local_repo }}'
    # update=yes will "git reset --hard", which could lose local
    # changes, which could be bad.
    update: no

- name: Link lnmgr into {{ user_bin_dir }}
  file:
    state: link
    src: '{{ lnmgr_local_repo | relpath(user_bin_dir) }}/lnmgr'
    dest: '{{ user_bin_dir }}/lnmgr'

- name: Clone dotfiles repository
  git:
    repo: '{{ dotfiles_remote_repo }}'
    dest: '{{ dotfiles_local_repo }}'
    update: no

- name: Install dotfiles
  command:
    argv: [
      '{{ lnmgr }}', -d, '{{ dotfiles_local_repo }}',
                     -t, '{{ ansible_env.HOME }}',
                     --if-changed, '101',
                     common
    ]
  register: lnmgr_res
  failed_when: 'lnmgr_res.rc not in (0, 101)'
  changed_when: 'lnmgr_res.rc == 101'

- name: Clone dotfiles-private repository
  git:
    repo: '{{ dotfiles_private_remote_repo }}'
    dest: '{{ dotfiles_private_local_repo }}'
    update: no
  tags: [dotfiles-private]

- name: Install dotfiles-private
  command:
    argv: [
      '{{ lnmgr }}', -d, '{{ dotfiles_private_local_repo }}',
                     -t, '{{ ansible_env.HOME }}',
                     --if-changed, '101',
                     '{{ dotfiles_private_which }}'
    ]
  register: lnmgr_res
  failed_when: 'lnmgr_res.rc not in (0, 101)'
  changed_when: 'lnmgr_res.rc == 101'
  tags: [dotfiles-private]
