system_app_dir: '/Applications'
user_app_dir: '{{ ansible_env.HOME }}/Applications'
user_bin_dir: '{{ ansible_env.HOME }}/bin'
user_font_dir: '{{ ansible_env.HOME }}/Library/Fonts'
repositories_root: '{{ ansible_env.HOME }}/repositories'
