dockutil_remote_repo: https://github.com/kcrawford/dockutil.git
dockutil_local_repo: '{{ repositories_root }}/dockutil'
dockutil: '{{ user_bin_dir }}/dockutil'
dockutil_defaults_to_remove:
  - Siri
  - Launchpad
  - Safari
  - Contacts
  - Calendar
  - Notes
  - Reminders
  - Maps
  - Photos
  - Messages
  - FaceTime
  - News
  - iTunes
  - Music
  - Podcasts
  - TV
  - App Store
  - System Preferences
  - Numbers
  - Keynote
  - Pages
  - Freeform
