- name: Clone Emacs Git repo
  dsedivec.ansible_dlc.x_git:
    repo: https://git.savannah.gnu.org/git/emacs.git
    dest: '{{ emacs_src_dir }}'
    # Make this conditional, since I usually want to control when I
    # rebuild Emacs.
    update: '{{ software_emacs_git_update }}'
    version: master
  register: git_clone_emacs

- name: Install Emacs dependencies
  homebrew:
    state: present
    update_homebrew: true
    name:
      - autoconf
      - automake
      - jansson
      - cairo
      - libxpm
      - libpng
      - jpeg
      - libtiff
      - giflib
      - librsvg
      - gnutls
      - libxml2
      - ccache
      - texinfo
      # native-comp
      - gcc
      - libgccjit
      # org-mode needs this to build.
      - gnu-tar
      - tree-sitter
  tags: [slow]

- name: Check for Emacs.app installed
  stat:
    path: '{{ user_app_dir }}/Emacs.app'
  register: emacs_app_stat

- name: Build and install Emacs
  script: build_install_ns_port.sh
  args:
    chdir: '{{ emacs_src_dir }}'
  when: >
    git_clone_emacs is changed
    or not emacs_app_stat.stat.exists
    or software_emacs_force_build_emacs

- name: Make bin directory
  file:
    state: directory
    path: '{{ user_bin_dir }}'

- name: Symlink emacsclient into bin directory
  file:
    state: link
    path: '{{ user_bin_dir }}/emacsclient'
    src: '{{ (user_app_dir + "/Emacs.app/Contents/MacOS/bin/emacsclient") | relpath(user_bin_dir) }}'

- name: Clone dot-emacs-d repository
  dsedivec.ansible_dlc.x_git_update:
    repo: '{{ dot_emacs_d_remote_repo }}'
    dest: '{{ dot_emacs_d_local_repo }}'
    update_mode: rebase-autostash

- name: Clone org-mode repository
  dsedivec.ansible_dlc.x_git:
    repo: '{{ org_mode_remote_repo }}'
    dest: '{{ org_mode_local_repo }}'
    # This is conditional for the same reason Emacs itself is: this
    # repo sees lots of commits and I want to control when I update
    # org-mode, rather than potentially rebuilding it multiple times
    # per day.
    update: '{{ software_emacs_git_update }}'
    # We must allow non-fast-forward updates, as I'm maintaining
    # patches atop upstream.  This may lose local commits that I
    # forget to push---value your reflog!  I should make this better.
    fast_forward: no
  register: git_org_mode

- name: Add org-mode upstream remote
  dsedivec.ansible_dlc.git_remote:
    repo: https://git.savannah.gnu.org/git/emacs/org-mode.git
    dest: '{{ org_mode_local_repo }}'
    remote: upstream
    state: present

- name: Rebase my org-mode changes atop upstream
  script: rebase_org_mode.sh
  args:
    chdir: '{{ org_mode_local_repo }}'
  register: org_rebase
  failed_when: 'org_rebase.rc not in (0, 111)'
  changed_when: 'org_rebase.rc == 111'
  when: 'software_emacs_git_update | bool'

- name: Put Emacs in the Dock
  command:
    argv: [
      '{{ dockutil }}', --add, '{{ user_app_dir }}/Emacs.app', --no-restart
    ]
  when: not emacs_app_stat.stat.exists
  notify:
    - Restart Dock
