- name: Clone dockutil repo
  git:
    repo: '{{ dockutil_remote_repo }}'
    dest: '{{ dockutil_local_repo }}'
    update: no

- name: Symlink dockutil into '{{ user_bin_dir }}'
  file:
    state: link
    src: '{{ (dockutil_local_repo + "/scripts") | relpath(user_bin_dir) }}/dockutil'
    dest: '{{ user_bin_dir }}/dockutil'

- name: Read list of things in the Dock
  shell: '{{ dockutil | quote }} --list | cut -f1'
  changed_when: false
  check_mode: no
  register: things_in_dock

- name: Set fact for list of things in the Dock
  set_fact:
    macos_dock_items: '{{ things_in_dock.stdout_lines | map("trim") | list }}'

- name: Remove default Dock items I don't want
  command:
    argv: ['{{ dockutil }}', --remove, '{{ item }}', --no-restart]
  when: 'item in macos_dock_items'
  notify: Restart Dock
  loop: '{{ dockutil_defaults_to_remove }}'

- name: Put Activity Monitor on the Dock
  command:
    argv: ['{{ dockutil }}',
           --add,
           '/System/Applications/Utilities/Activity Monitor.app',
           --no-restart]
  when: '"Activity Monitor" not in macos_dock_items'
  notify: Restart Dock
