- name: Clone dockutil repo
  git:
    repo: '{{ dockutil_remote_repo }}'
    dest: '{{ dockutil_local_repo }}'
    update: no
  register: dockutil_clone

- name: Check if dockutil is installed
  ansible.builtin.stat:
    path: '{{ user_bin_dir }}/dockutil'
  register: dockutil_stat
  when: 'dockutil_clone is not changed'

- name: Build dockutil
  command:
    argv: ['./build.sh']
    chdir: '{{ dockutil_local_repo }}'
  when: 'dockutil_clone is changed or (dockutil_stat is defined and not dockutil_stat.stat.exists)'

- name: Install dockutil into '{{ user_bin_dir }}'
  ansible.builtin.copy:
    src: '{{ dockutil_local_repo }}/.build/release/dockutil'
    dest: '{{ user_bin_dir }}/dockutil'
    mode: 0755

- name: Read list of things in the Dock
  shell: '{{ dockutil | quote }} --list | cut -f1'
  changed_when: false
  check_mode: no
  register: things_in_dock

- name: Set fact for list of things in the Dock
  set_fact:
    macos_dock_items: '{{ things_in_dock.stdout_lines | map("trim") | list }}'

- name: Remove default Dock items I don't want
  command:
    argv: ['{{ dockutil }}', --remove, '{{ item }}', --no-restart]
  when: 'item in macos_dock_items'
  notify: Restart Dock
  loop: '{{ dockutil_defaults_to_remove }}'

- name: Put Activity Monitor on the Dock
  command:
    argv: ['{{ dockutil }}',
           --add,
           '/System/Applications/Utilities/Activity Monitor.app',
           --no-restart]
  when: '"Activity Monitor" not in macos_dock_items'
  notify: Restart Dock
