- name: Install Node.js, NPM, Hugo
  x_macports:
    state: present
    name: [npm6, hugo +extended]
  become: yes

- name: Install web development packages from NPM
  npm:
    state: present
    global: yes
    name: '{{ item }}'
  loop: [csslint, js-beautify, eslint, tern, netlify]
