- name: Set ComputerName
  shell: scutil --set ComputerName {{ computer_name | quote }}

- name: Set LocalHostName
  shell: scutil --set LocalHostName {{ inventory_hostname | quote }}

- name: Check firewall status
  command: /usr/libexec/ApplicationFirewall/socketfilterfw --getglobalstate
  changed_when: false
  register: firewall_state

- name: Enable the firewall
  command: /usr/libexec/ApplicationFirewall/socketfilterfw --setglobalstate on
  when: >
    "firewall is enabled" not in (firewall_state.stdout | default("")).lower()
  become: yes

# Suggested by http://docs.hardentheworld.org/OS/MacOS_10.12_Sierra/index.html
- name: Enable "Require an administrator password to access system-wide preferences"
  osx_auth_policy_db:
    key: shared
    type: bool
    value: false
  become: yes
