- name: Install Go development tools
  command:
    argv: [go, install, '{{ item }}']
    creates: >-
      {{ go_bin_dir }}/{{ item | regex_replace("^.+/([^@]+)(?:@.*)?$", "\\1") }}
  environment:
    GO111MODULE: 'on'
  loop:
    - 'golang.org/x/tools/gopls@latest'
    - 'mvdan.cc/gofumpt@master'
