- name: Install Pythons
  macports:
    state: present
    name: [python27, py27-virtualenv, python38]
  become: yes

- name: Check "python3" executable
  stat:
    path: /opt/local/bin/python3
  register: python3_stat

- name: Make "python3" point at latest Python 3 version
  command: port select --set python3 python38
  become: yes
  when: >
    python3_stat.stat.islnk is not defined
    or not python3_stat.stat.islnk
    or python3_stat.stat.lnk_target != "/opt/local/bin/python3.8"

- name: Build Python 2.7 virtualenv
  command:
    argv: [/opt/local/bin/virtualenv-2.7, '{{ user_py2_venv_dir }}']
    creates: '{{ user_py2_venv_bin }}/activate'
  register: virtualenv

- name: Upgrade pip in 2.7 virtualenv
  command:
    argv: ['{{ user_py2_venv_bin }}/pip', 'install', '--upgrade', 'pip']
  when: virtualenv is changed

- name: Build Python 3.8 virtualenv
  command:
    argv: [/opt/local/bin/python3.8, '-m', venv, '{{ user_py3_venv_dir }}']
    creates: '{{ user_py3_venv_bin }}/activate'
  register: virtualenv

- name: Upgrade pip in 3.8 virtualenv
  command:
    argv: ['{{ user_py3_venv_bin }}/pip', 'install', '--upgrade', 'pip']
  when: virtualenv is changed
