- name: Install MacTeX
  command:
    argv:
      - '{{ macfit }}'
      - http://mirror.ctan.org/systems/mac/mactex/MacTeX.pkg
      - --check-pkg-signature
      - 'id:RBGCY5RJWM'
      # --owner can't affect the pkg here, but it can make sure the
      # --cached download is owned by our user.
      - --owner
      - '{{ ansible_user }}'
      - --cache-dir
      - '{{ ansible_env.HOME }}/Downloads'
  become: true
  when: ('org.tug.mactex.texlive2019' not in macos_installed_pkgs)
        or ('org.tug.mactex.gui2019' not in macos_installed_pkgs)
