- name: Install MacTeX
  homebrew_cask:
    state: installed
    name: mactex
    path: '{{ homebrew_sudo_wrapper | dirname }}'
  become: yes

# Installing Ghostscript from Homebrew (see below) may install
# pkg-config?  This is bad since it ends up shadowing MacPorts's
# pkg-config (via my .bashrc), and MacPorts is where I actually
# install all my libraries.  Make sure pkg-config isn't installed by
# Homebrew.
- name: Uninstall Homebrew pkg-config
  homebrew:
    state: absent
    name: pkg-config

# Homebrew (annoyingly) disables installing Ghostscript with MacTeX,
# so you have to tell LaTeXiT where to find Homebrew's Ghostscript and
# ps2pdf.
- name: Tell LaTeXiT where to find Homebrew's Ghostscript
  x_osx_defaults:
    domain: fr.chachatelier.pierre.LaTeXiT
    key:
      - CompositionConfigurations
      - 0
      - additionalProcessingScripts
      - '{{ item.key }}'
    container_types: [dict, array, dict]
    value_type: string
    value: '{{ item.value }}'
  loop:
    - key: gsPath
      value: '{{ homebrew_bin }}/gs'
    - key: psToPdfPath
      value: '{{ homebrew_bin }}/ps2pdf'
