# I am not at all confident that Dropbox will tolerate being installed to
# ~/Applications, so put it in /Applications.
- name: Install Dropbox
  homebrew_cask:
    state: installed
    name: dropbox
    path: '{{ homebrew_sudo_wrapper | dirname }}'
  become: yes
