- name: Install sqlint
  gem:
    state: present
    name: sqlint

- name: Install pgcli
  pip:
    virtualenv: '{{ user_py3_venv_dir }}'
    name: pgcli
    state: present

- name: Symlink pgcli into {{ user_bin_dir }}
  file:
    state: link
    src: '{{ user_py3_venv_bin }}/pgcli'
    dest: '{{ user_bin_dir }}/pgcli'
    # Another use of force only when in check mode, since the source
    # file doesn't exist due to the prior task not having been run.
    force: '{{ ansible_check_mode }}'
