- name: Install PostgreSQL
  x_macports:
    name:
      - 'postgresql{{ software_dev_sql_postgresql_version }}'
      - 'postgresql{{ software_dev_sql_postgresql_version }}-server'
    state: present
  become: true
  tags: [slow]

- name: Select PostgreSQL {{ software_dev_sql_postgresql_version }}
  command:
    argv:
      - port
      - select
      - --set
      - postgresql
      - 'postgresql{{ software_dev_sql_postgresql_version}}'
    creates: /opt/local/bin/pg_config
  become: yes

- name: Install sqlint
  gem:
    state: present
    name: sqlint

- name: Install pgcli
  pip:
    virtualenv: '{{ user_py3_venv_dir }}'
    name: pgcli
    state: present

- name: Symlink pgcli into {{ user_bin_dir }}
  file:
    state: link
    src: '{{ user_py3_venv_bin }}/pgcli'
    dest: '{{ user_bin_dir }}/pgcli'
