- name: Find MacTeX fonts
  find:
    paths:
      - /Library/TeX/Root/texmf-dist/fonts
    patterns:
      - AnonymousPro-*.ttf
      - Crimson-*.otf
      - CrimsonPro-*.ttf
      - EBGaramond-*.otf
      - FiraMono-*.otf
      - Gentium*.ttf
      - Inconsolata*.otf
      - Lato-*.ttf
      - NotoSerif-*.otf
      - SourceCodePro-*.otf
    recurse: true
    follow: true
  register: mactex_fonts

- name: Hard link found fonts into ~/Library/Fonts
  file:
    state: hard
    #src: '{{ item | relpath(ansible_env.HOME + "/Library/Fonts") }}'
    src: '{{ item }}'
    dest: '{{ ansible_env.HOME }}/Library/Fonts/{{ item | basename }}'
  loop: '{{ mactex_fonts.files | map(attribute="path") | list }}'
